baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Kasthuri Rengarajan"
copyright = 'Kasthuri'
enableRobotsTXT = true

theme = "til"


[menus]
  [[menus.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 30

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startLevel = 1

[params]
description = "Kasthuri musings about machine learning and other aspects."

  [params.author]
    name = 'Kasthuri Rengarajan'
    email = 'kasthuri.r7903@gmail.com'

  [params.footer]
    creativeCommonsLicense = 'by_sa'

  [params.robotstxt]
    blockCC = true
    blockAI = true
